# credit [to](https://stackoverflow.com/a/78766052)
name: require merge from main split of split branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check split branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != *\/* ]]
          then
            echo "Branch is not a split branch."
            exit 0
          else if [[ ${GITHUB_HEAD_REF} != *\/main ]]
          then
              exit 1
          fi
